name: Notify on Released Label

on:
  issues:
    types: [labeled]

permissions:
  contents: read       # needed for getLatestRelease
  issues: write        # needed for createComment

jobs:
  notify-released:
    if: ${{ github.event.label.name == 'Released' }}
    runs-on: ubuntu-latest

    steps:
      - name: Comment with latest release info
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.payload.issue.number;

            // Fetch the latest release via REST API
            const { data: release } = await github.rest.repos.getLatestRelease({
              owner,
              repo
            });

            const version = release.tag_name;
            const url = release.html_url;

            const body = [
              `Hi! This issue has been **Resolved** as part of **${version}**!`,
              `Please verify the fix in the [release ${version}](${url}).`,
              "If you still see a problem, please let me know."
            ].join("\n\n");

            // Post comment on the issue
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body
            });
